### ISSUE TITLE
[Request] Add ReadMe for the project

### ISSUE THREAD

**Issue by RafayGhafoor** [wajeehmisbahkhan/FAST-NUCES#3]
I would really appreciate if you could add a brief introduction about the project and how to build it.

**Comment by wajeehmisbahkhan** [comment]
@RafayGhafoor 
Please confirm if you are able to get the project running by following the readme. Thank you.

**Comment by RafayGhafoor** [comment]
@wajeehmisbahkhan, I am able to get the project running but unable to login.

![image](https://user-images.githubusercontent.com/20343475/75959313-cc81d480-5edf-11ea-89d8-63ac8e4d61ff.png)

**Comment by wajeehmisbahkhan** [comment]
You can go to the firebase console and select the project you have created. Create an account in the firebase authentication tab with an email and password and use that to login. You can follow the starting of this tutorial for that:
https://youtu.be/qP5zw7fjQgo
